config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  resources :users
  put '/user_search', controller: 'users', action: :user_search

  resources :groups do
    put ':id', action: :show, as: :select
    post 'add_user/:user_id', action: :add_user, as: :add_user
    resources :turnpoints, controller: 'groups/turnpoints'
  end

  root 'home#index'

  get '/.well-known/brave-rewards-verification.txt', to: redirect('/brave-rewards-verification.txt')

  get '/terms_and_conditions', to: "home#terms_and_conditions"
  get '/privacy_policy', to: "home#privacy_policy"
  put "accept_terms_and_purchase", to: "home#accept_terms_and_purchase"

  namespace :api do
    resources :groups do
      get :most_recent_waypoints
      get :sar_json
    end

    post :external_source_tracker, to: 'external_trackpoints#create'
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groupings, dependent: :destroy
  has_and_belongs_to_many :users, join_table: 'user_groupings'

  accepts_nested_attributes_for :user_groupings

  has_many :turnpoints

  validates :name, presence: true
end

app/models/turnpoint.rb
class Turnpoint < ApplicationRecord
  belongs_to :group

  scope :sorted, -> { order(sort_order: :asc) }
  scope :active, -> { where(active: true) }
end

app/controllers/api/groups_controller.rb
module Api
  class GroupsController < ApplicationController
    layout false

    def most_recent_waypoints
      @most_recent_waypoints = []
      @group = Group.find_by(params[:id])

      if params[:debug] == "true"
        users = User
      else
        users = @group.users
      end

      users.with_waypoints.each do |user|
        @most_recent_waypoints << user.waypoints.order(:created_at).last.attributes.merge({pilot_id: user.id, map_link: "https://www.xctrack.me/?pilots=#{user.id}"})
      end


      render json: {last_known_waypoints: @most_recent_waypoints}
    end

    def sar_json
      render file: 'public/trackpoints.json'
    end

  end
end

app/controllers/groups/turnpoints_controller.rb
module Groups
  class TurnpointsController < ApplicationController

    def edit
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])
    end

    def update
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])
      @turnpoint.update!(turnpoint_params)

      redirect_to edit_group_path(@group)
    end

    def new
      @group = Group.find(params[:group_id])
    end

    def create
      @group = Group.find(params[:group_id])
      @group.turnpoints.create!(turnpoint_params)

      redirect_to edit_group_path(@group)
    end

    def destroy
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])

      @turnpoint.destroy

      redirect_to edit_group_path(@group)
    end

    private
      def turnpoint_params
        params.require(:turnpoint).permit(:name, :latitude, :longitude, :radius, :active, :sort_order, :color)
      end

  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def index
    @groups = Group.all
    if current_user
      @user_groups = current_user.groups
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      flash[:success] = 'Group was successfully created.'
      redirect_to edit_group_path(@group)
    else
      render :new
    end

  end

  def edit
    @edit = true
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:success] = 'Group was successfully updated'
      redirect_to groups_path
    else
      render :edit
    end

  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def show
    @group = Group.includes(:users).find(params[:id])
    @current_group_id = @group.id

    fetch_users(@group)

    @coordinates = @users_on_map.map(&:fetch_coordinates)
    render 'home/index'
  end

  def add_user
    @group = Group.find(params[:group_id])
    @group.user_groupings.create(user_id: params[:user_id])
    redirect_to edit_group_path(@group)
  end

  private
    def group_params
      params.require(:group).permit(:name, user_grouping_ids: [])
    end

end

app/views/groups/turnpoints/_form.html.haml
- if edit
  = form_for @turnpoint, url: group_turnpoint_path(@group, @turnpoint) do |f|
    .form-group
      .row
        .col-md-6
          %label Name
          = f.text_field :name, class: 'form-control', required: true
        .col-md-3
          %label Color
          = f.select :color, options_for_select([['Red', '#FF0000'], ['Green', '#00FF00'], ['Yellow', '#FFFF00']], @turnpoint.color), {}, class: 'form-control'

        .col-md-3
          %label{style: 'padding-top:20px;'}
            = f.check_box :active
            Active?
      %hr
    .form-group
      .row
        .col-md-6
          %label Latitude
          = f.number_field :latitude, class: 'form-control', required: true, step: 0.00000000000001
        .col-md-6
          %label Longitude
          = f.number_field :longitude, class: 'form-control', required: true, step: 0.00000000000001
      %hr
    .form-group
      .row
        .col-md-6
          %label Radius (meters)
          = f.number_field :radius, class: 'form-control', required: true
        .col-md-6
          %label Sort Order
          = f.number_field :sort_order, class: 'form-control'
      %hr

    .row
      .col-md-12
        = f.submit 'Update', class: 'btn btn-primary btn-sm'
- else
  = form_for :turnpoint, url: group_turnpoints_path(@group) do |f|
    .form-group
      .row
        .col-md-6
          %label Name
          = f.text_field :name, class: 'form-control', required: true
        .col-md-3
          %label Color
          = f.select :color, options_for_select([['Red', '#FF0000'], ['Green', '#00FF00'], ['Yellow', '#FFFF00']]), {}, class: 'form-control'
        .col-md-3

          %label{style: 'padding-top:20px;'}
            = f.check_box :active
            Active?
      %hr
    .form-group
      .row
        .col-md-6
          %label Latitude
          = f.number_field :latitude, class: 'form-control', required: true, step: 0.00000000000001
        .col-md-6
          %label Longitude
          = f.number_field :longitude, class: 'form-control', required: true, step: 0.00000000000001
      %hr
    .form-group
      .row
        .col-md-6
          %label Radius (meters)
          = f.number_field :radius, class: 'form-control', required: true
        .col-md-6
          %label Sort Order
          = f.number_field :sort_order, class: 'form-control'
      %hr

    .row
      .col-md-12
        = f.submit 'Create', class: 'btn btn-primary btn-sm'

app/views/groups/turnpoints/edit.js.erb
$('#editModal .modal-body')
  .html('<%= j(render partial: "groups/turnpoints/form", locals: {edit: true}) %>');

$('#editModal').modal('show');

app/views/groups/turnpoints/new.js.erb
$('#editModal .modal-body')
  .html('<%= j(render partial: "groups/turnpoints/form", locals: {edit: false}) %>');

$('#editModal').modal('show');