config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  resources :users
  put '/user_search', controller: 'users', action: :user_search

  resources :groups do
    put ':id', action: :show, as: :select
    post 'add_user/:user_id', action: :add_user, as: :add_user
    resources :turnpoints, controller: 'groups/turnpoints'
  end

  root 'home#index'

  get '/.well-known/brave-rewards-verification.txt', to: redirect('/brave-rewards-verification.txt')

  get '/terms_and_conditions', to: "home#terms_and_conditions"
  get '/privacy_policy', to: "home#privacy_policy"
  put "accept_terms_and_purchase", to: "home#accept_terms_and_purchase"

  namespace :api do
    resources :groups do
      get :most_recent_waypoints
      get :sar_json
    end

    post :external_source_tracker, to: 'external_trackpoints#create'
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groupings, dependent: :destroy
  has_and_belongs_to_many :users, join_table: 'user_groupings'

  accepts_nested_attributes_for :user_groupings

  has_many :turnpoints

  validates :name, presence: true
end

app/controllers/api/groups_controller.rb
module Api
  class GroupsController < ApplicationController
    layout false

    def most_recent_waypoints
      @most_recent_waypoints = []
      @group = Group.find_by(params[:id])

      if params[:debug] == "true"
        users = User
      else
        users = @group.users
      end

      users.with_waypoints.each do |user|
        @most_recent_waypoints << user.waypoints.order(:created_at).last.attributes.merge({pilot_id: user.id, map_link: "https://www.xctrack.me/?pilots=#{user.id}"})
      end


      render json: {last_known_waypoints: @most_recent_waypoints}
    end

    def sar_json
      render file: 'public/trackpoints.json'
    end

  end
end

app/controllers/groups/turnpoints_controller.rb
module Groups
  class TurnpointsController < ApplicationController

    def edit
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])
    end

    def update
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])
      @turnpoint.update!(turnpoint_params)

      redirect_to edit_group_path(@group)
    end

    def new
      @group = Group.find(params[:group_id])
    end

    def create
      @group = Group.find(params[:group_id])
      @group.turnpoints.create!(turnpoint_params)

      redirect_to edit_group_path(@group)
    end

    def destroy
      @group = Group.find(params[:group_id])
      @turnpoint = Turnpoint.find(params[:id])

      @turnpoint.destroy

      redirect_to edit_group_path(@group)
    end

    private
      def turnpoint_params
        params.require(:turnpoint).permit(:name, :latitude, :longitude, :radius, :active, :sort_order, :color)
      end

  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def index
    @groups = Group.all
    if current_user
      @user_groups = current_user.groups
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      flash[:success] = 'Group was successfully created.'
      redirect_to edit_group_path(@group)
    else
      render :new
    end

  end

  def edit
    @edit = true
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:success] = 'Group was successfully updated'
      redirect_to groups_path
    else
      render :edit
    end

  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def show
    @group = Group.includes(:users).find(params[:id])
    @current_group_id = @group.id

    fetch_users(@group)

    @coordinates = @users_on_map.map(&:fetch_coordinates)
    render 'home/index'
  end

  def add_user
    @group = Group.find(params[:group_id])
    @group.user_groupings.create(user_id: params[:user_id])
    redirect_to edit_group_path(@group)
  end

  private
    def group_params
      params.require(:group).permit(:name, user_grouping_ids: [])
    end

end

app/views/groups/_form.html.haml
- if @group.errors.any?
  #error_expl.panel.panel-danger
    .panel-heading
      %h3.panel-title
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
    .panel-body
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
.row
  .col-md-6
    .form-group
      .row
        .col-md-6
          %label Name
          = f.text_field :name, class: 'form-control'

    .form-group
      = f.submit nil, :class => 'btn btn-primary'

    .form-group
      - if @group.persisted?
        =link_to group_path(@group), class: 'btn btn-success btn-sm' do
          View Group Map
  - if @edit
    .col-md-6
      %h1
      .well
        %ul.list-group
          %li.list-group-item
            = text_field_tag '[user_name]', nil, placeholder: "Add pilots to group", class: 'form-control user-search', autocomplete: "off"
            #search-results.hidden
              .well.well-sm.well-default
            = f.collection_check_boxes :user_grouping_ids, @group.user_groupings.all, :id, :group_id do |b|
              %li.list-group-item
                = b.check_box(checked: "checked")
                = b.object.user.name


:javascript
  $(function(){
    $('.user-search').keyup(function(){
      value = $(this).val();
      if (value.length >= 3){
        $.ajax({
          method: 'PUT',
          url: '/user_search',
          data: {name: value, group_id: #{@group.id}},
        })
      }
      else{
        $('#search-results').addClass('hidden').find('.well').html();
      }
    });
  })

app/views/groups/edit.html.haml
.row
  .col-md-12
    = bootstrap_flash
.page-header
  %h1 Edit Group
  = form_for @group, url: group_path(@group), method: :put do |f|
    = render :partial => 'form', locals: {f: f}

%h3 Turnpoints

= link_to new_group_turnpoint_path(@group), remote: true, class: 'btn btn-sm btn-secondary' do
  Add New

.list-group
  - @group.turnpoints.sorted.each do |turnpoint|
    .list-group-item

      %strong
        = turnpoint.name
        %div{style: "float: left; height: 10px; width: 10px; margin: 5px 5px 0 0;background-color: #{turnpoint.color};"} &nbsp

      %br

      %em Latitude:
      #{turnpoint.latitude}

      %br

      %em Longitude:
      #{turnpoint.longitude}
      %br

      %em Radius (meters):
      #{turnpoint.radius}

      %br

      %em Sort Order:
      #{turnpoint.sort_order}

      %br

      %em Active
      #{turnpoint.active}

      %br
      = link_to edit_group_turnpoint_path(@group, turnpoint), remote: true do
        %i.fa.fa-pencil
        edit
      || ------ ||

      = link_to group_turnpoint_path(@group, turnpoint), method: :delete, data: {confirm: 'Are you sure you want to delete this turnpoint?'} do
        %i.fa.fa-trash.text-danger
        destroy




#editModal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body

app/views/groups/index.html.haml
.row
  .col-md-12
    = bootstrap_flash

.page-header
  %h1
    My Groups
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Name
      %th Member Count
      %th Created At
      %th Manage
  %tbody
    - @user_groups.each do |group|
      %tr
        %td= link_to group.id, group_path(group)
        %td= link_to group.name, group_path(group)
        %td= group.users.count
        %td= l group.created_at
        %td
          - if group.users.includes(current_user)
            = link_to 'Edit', edit_group_path(group), class: 'btn btn-default btn-xs'
            - if current_user.admin?
              = link_to 'Delete', group_path(group), class: 'btn btn-danger btn-xs',  :method => :delete,:data => { :confirm => 'Deleting this group will remove it for all members. Continue?'}
.page-header
  %h1
    All Groups
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Name
      %th Member Count
      %th Created At
      - if current_user.admin?
        %th extra buttons
  %tbody
    - @groups.each do |group|
      %tr
        %td= link_to group.id, group_path(group)
        %td= group.name
        %td= group.users.count
        %td= l group.created_at
        %td
          = link_to 'Edit', edit_group_path(group), class: 'btn btn-default btn-xs'
          - if current_user.admin?
            = link_to 'Delete', group_path(group), class: 'btn btn-danger btn-xs',  :method => :delete,:data => { :confirm => 'sup?'}

= link_to t('.new', :default => t("helpers.links.new")), new_group_path, :class => 'btn btn-primary'

app/views/groups/new.html.haml
.page-header
  %h1 New Group
  = form_for @group, url: groups_path, method: :post do |f|
    = render :partial => 'form',locals: {f: f}