config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  resources :users
  put '/user_search', controller: 'users', action: :user_search

  resources :groups do
    put ':id', action: :show, as: :select
    post 'add_user/:user_id', action: :add_user, as: :add_user
    resources :turnpoints, controller: 'groups/turnpoints'
  end

  root 'home#index'

  get '/.well-known/brave-rewards-verification.txt', to: redirect('/brave-rewards-verification.txt')

  get '/terms_and_conditions', to: "home#terms_and_conditions"
  get '/privacy_policy', to: "home#privacy_policy"
  put "accept_terms_and_purchase", to: "home#accept_terms_and_purchase"

  namespace :api do
    resources :groups do
      get :most_recent_waypoints
      get :sar_json
    end

    post :external_source_tracker, to: 'external_trackpoints#create'
  end

end

app/views/shared/_google_analytics.html.erb
<%- return unless Rails.env.production? %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87655988-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_pilot_container.html.haml
#pilots-container{class: ('hidden' if @users_on_map.any?)}
  .col-lg-4.col-md-6.col-xs-11.no-padding.pilot-container-block
    -if current_user && !current_user.accepted_terms_and_privacy
      - # someone is logged in, and they have not accepted the terms + privacy yet
      .well{style:'padding: 20px; 0'}
        %p
          We've updated our
          = link_to "Terms & Conditions", terms_and_conditions_path, target:"_blank", style: 'text-decoration:underline;'
          &
          = link_to "Privacy Policy", privacy_policy_path, target:"_blank", style: 'text-decoration:underline;'

        %p Click the links above to read. Once you've read them, you can accept them by clicking the button below.

        =link_to "I Accept", accept_terms_and_purchase_path, class: 'btn btn-primary', method: :put
    - else

      %ul.list-group{style: 'margin: 0'}
        = render 'shared/pilot_order_buttons'
      .well
        %ul.list-group{style: 'margin-bottom: 10px;'}
          #pilot-names
            = render partial: 'shared/pilots_on_map'
        .row
          - if @group.present?
            .col-md-6.form-group
              = link_to 'edit group', edit_group_path(@group), class: 'btn btn-sm btn-default btn-block'

app/views/shared/_pilot_container_toggle.html.haml
- if params[:controller] == 'home' || (params[:controller] == 'groups' && params[:action] == 'show' )
  %li
    %p.navbar-btn.toggle-pilot-container
      = link_to "Add Pilots to Map", "#", class: 'btn btn-primary', style: 'color: #FFF;'

app/views/shared/_pilot_order_buttons.html.haml
.list-group-item
  .row
    .col-xs-6
      #updateMapButton.btn.btn-primary.btn-block{onclick: "$('#pilot-names form').submit();", class: (' disabled' unless @users_on_map.any?)}
        Show Map
      
    .col-xs-6
      %select.form-control{onchange: "pickGroup($(this));"}
        %option{selected: 'selected', data: {url: root_path } }
          = "All Groups"

        - Group.order(name: :asc).includes(:users).each do |group|
          - next if group.users.empty?
          %option{selected: ('selected' if group.id == params[:id].to_i ), data: {url:group_path(group)} }
            = "#{group.name} (#{group.users.length} pilots)"

        %option{data: {url: new_group_path}}
          = "New Group"
 
    
:javascript
    function pickGroup(el){
      var $this = el
      var data = $this.find(':selected').data('url');
      location.assign(data)
    }

app/views/shared/_pilots_on_map.html.haml
- path = @current_group_id.present? ? group_path(@current_group_id) : root_path

= form_tag path, method: :get do
  - @users.each do |user|
    - next unless user.most_recent_flight.present?
    - length = user.most_recent_flight.flight_length
    - straight_distance = user.most_recent_flight.straight_line_distance

    - if user.waypoints.order(:timestamp).last&.timestamp.present?
      - last_point = distance_of_time_in_words((user.waypoints.order(:timestamp).last&.timestamp || Time.now), Time.now)
    - else
      - last_point = "N/A"
    %li.list-group-item.pilot-on-map{data: {flight_length: length, name: user.name, straight_distance: straight_distance}}
      .row
        .col-xs-4.col-sm-4
          -if @rendered_user_ids.include?(user.id)
            %a.btn.btn-default.btn-success.btn-block.pilot-toggle-button.remove-pilot-btn{data: {pilot_id: user.id}}
              &#10003;
          -else
            %a.btn.btn-default.btn-default.btn-block.pilot-toggle-button.add-pilot-btn{data: {pilot_id: user.id}}
              &#43;

        .col-xs-8.col-sm-8
          .text-center
            = link_to user_path(user) do
              = user.name
              %br
              %small
                = last_point
                ago
                &#8226;
                &Delta;
                = length
                km
                &#8226
                |
                = straight_distance
                km

  = hidden_field_tag 'pilots', @rendered_user_ids.join(',')
  = submit_tag 'Update Map', name: nil, class: 'hidden'



- if @users.empty?
  %li.list-group-item
    Hmm, it must be unflyable today :(

= link_to 'FREE FLIGHT LAB', 'http://www.freeflightlab.org', target:'_blank', class: 'ffl-logo'

app/views/shared/_time_select.html.haml
.list-group-item
  .row
    .col-xs-4
      .btn.btn-sm.btn-block.btn-success
        24h
    .col-xs-4
      / .btn.btn-sm.btn-default.btn-block
      /   24h
    .col-xs-4
      / .btn.btn-sm.btn-default.btn-block
      /   48h

app/views/shared/_user_search_results.html.haml
.list-group
  - users.each do |user|
    - if user.groups.include?(@group)
      .list-group-item.disabled
        = user.name
        (already in group)
    - else
      = link_to group_add_user_path(@group, user.id), method: :post, class: 'list-group-item' do
        = user.name
  -if users.empty?
    No results :(