config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  resources :users
  put '/user_search', controller: 'users', action: :user_search

  resources :groups do
    put ':id', action: :show, as: :select
    post 'add_user/:user_id', action: :add_user, as: :add_user
    resources :turnpoints, controller: 'groups/turnpoints'
  end

  root 'home#index'

  get '/.well-known/brave-rewards-verification.txt', to: redirect('/brave-rewards-verification.txt')

  get '/terms_and_conditions', to: "home#terms_and_conditions"
  get '/privacy_policy', to: "home#privacy_policy"
  put "accept_terms_and_purchase", to: "home#accept_terms_and_purchase"

  namespace :api do
    resources :groups do
      get :most_recent_waypoints
      get :sar_json
    end

    post :external_source_tracker, to: 'external_trackpoints#create'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta property="og:title" content="<%= title_helper %>" />
    <title><%= title_helper %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <%= favicon_link_tag "/favicon.ico" %>

    <script data-ad-client="ca-pub-5155287976010304" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse <%= 'no-margin-vertical' if %w(home groups).include?(params[:controller]) %>" style="border-radius: 0;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <%= image_tag 'xctrack_logo.png', style: 'height:45px;float:left;margin: -12px 10px 0 0' %>
            XcTrack.me
          </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <%- if user_signed_in? %>
              <li style="margin-top: 6px;">
                <script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support XcTrack', '#46b798', 'W7W7EPPV');kofiwidget2.draw();</script>
              </li>
              <%= render partial: 'shared/pilot_container_toggle' %>
              <li class="visible-xs"><%= link_to "My Profile", user_path(current_user) %></li>
              <li class="visible-xs"><%= link_to "My Groups", groups_path %></li>
              <li role="separator" class="divider visible-xs"></li>
              <li class="visible-xs"><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
              <li class="visible-xs"><%= link_to "Terms", terms_and_conditions_path %></li>
              <li class="visible-xs"><%= link_to "Privacy Policy", privacy_policy_path %></li>


              <li class="dropdown hidden-xs">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Profile", user_path(current_user) %></li>
                  <li><%= link_to "My Groups", groups_path %></li>
                  <li><a href="mailto:aneigher@gmail.com">Contact Me</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Terms", terms_and_conditions_path %></li>
                  <li><%= link_to "Privacy Policy", privacy_policy_path %></li>

                </ul>
              </li>
            <% else %>
              <li style="margin-top: 6px;">
                <script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support XcTrack', '#46b798', 'W7W7EPPV');kofiwidget2.draw();</script>
              </li>
              <%= render partial: 'shared/pilot_container_toggle' %>
              <li><%= link_to('Sign Up', new_user_registration_path)  %></li>
              <li><%= link_to('Login', new_user_session_path)  %></li>
            <% end %>


          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
  <%= render partial: 'shared/google_analytics' %>
</html>